### PR TITLE
Optional params

### PR DESCRIPTION
**Pull request by noamokman**
Hi there @typicode,
Updated dependencies,
And made `args` and `out` params optional, on all platforms.
Thanks!

### CODE REVIEW

**Comment by derhuerst** [comment]
@noamokman Please update `.travis.yml` to test at least for `0.12`, `4`, `6` and `latest`.

@typicode Did you consider dropping the support for `0.12`?

**Comment by noamokman** [comment]
done @derhuerst

**Comment by noamokman** [comment]
@typicode @derhuerst dropping support for node 0.12 is a good idea :+1:

**Comment by typicode** [comment]
Thank you :+1: 
For Node 0.12, unfortunately, last time I checked it seemed to be still used a lot.

**Comment by typicode** [comment]
Published `v0.2.2` :)

**Pull request merged**
